%% ExtractAllSPIKES_BOOTSTRAP
%
% Bootstrap extraction and aggregation of spike activity across recording
% sessions.
%
% This function loads SUA session files, extracts spike trains according
% to the selected alignment mode, identifies valid neurons for monkeys S
% and K using the corresponding GoodCells files, and generates bootstrap
% populations by randomly sampling trials within each condition and
% direction.
%
% The original extraction and processing pipeline was developed as part of
% the project and is intentionally preserved. The current implementation only
% includes maintenance updates, improved path handling, parameter
% management, and output organization, without modifying the underlying
% scientific analysis.
%
% INPUT
%   M
%       Number of bootstrap repetitions.
%
%   params
%       Structure containing extraction parameters. Missing fields are
%       automatically completed using getDefaultSPIKESparamsBOOT().
%
% OUTPUT
%   data_trials_BS
%       Structure array containing bootstrap-aggregated spike matrices for
%       monkeys S and K together with trial metadata.
%
% OUTPUT FILES
%   Single-session extracted data:
%       <singleDir_save>/BOOT<M>/<irng>/Single_SpikesExtractedBOOT/
%
%   Aggregated bootstrap dataset:
%       <dir_save>/All_SpikesExtractedBOOT/
%
% NOTES
%   - Each bootstrap population is generated by randomly sampling one
%     compatible trial per session for each condition-direction pair.
%   - The scientific processing pipeline is preserved from the original
%     implementation.
%   - Parameters used during extraction are saved together with the final
%     output file for reproducibility.
%   - Random seed management is intentionally left to the calling script.
%
% HISTORY
%   Original implementation:
%       Lorenzo Ognibeni
%
%   Maintenance and integration updates:
%       Mirco Frosolone
%
%   Functional behaviour of the analysis pipeline has not been modified.
function data_trials_BS = ExtractAllSPIKES_BOOTSTRAP(M,params)

if nargin < 1 || isempty(M)
    error('ExtractAllSPIKES_BOOTSTRAP: M must be specified.');
end

if nargin < 2 || isempty(params)
    params = struct();
end


% default params
defParams = getDefaultSPIKESparamsBOOT;

% merge params
params = mergeParams(defParams, params);

fprintf('\n');
fprintf('================ SPIKES EXTRACTION PARAMETERS ================\n');
fprintf('Chamber        : %s\n', params.chamber);
fprintf('Time Interval  : [%g  %g] ms\n', params.interval(1), params.interval(2));
fprintf('Mode Aligned   : %s\n', modeAlignToString(params.MODE_ALIGN));
fprintf('Monkey         : %s\n', params.selMonkey);
fprintf('N. Sessions    : %d\n', numel(params.session_list.(params.chamber)));
fprintf('===============================================================\n\n');

interval        = params.interval; % [-200,500] ms
selMonkey       = params.selMonkey;
session_list    = params.session_list.(params.chamber);
MODE_ALIGN      = params.MODE_ALIGN;

% VARIABLES_monkey_joint_action;

for n_sess = 1:length(session_list)
    session_name = session_list{n_sess};
    try
        session_name = strcat(session_name,'H_SUA');
    catch
        fprintf('Spikes_translation Warning: using %s\n',session_name);
        pause;
    end
    d       = load(session_name);
    Trials  = d.Trials;
    chamber = Trials(1).Chamber;
    tic;
    fprintf('Getting data from %s\n',session_name);

    DataSpike = getSpikesJointAllNeurons(Trials);
    fprintf('Elapsed time: %g s\n',toc(tic))
    DataSpike = getSuccessfullTrials(DataSpike,Trials);
    DataSpike = getJointConditionTrials(DataSpike,Trials);
    DataSpike = getSolo_S_ConditionTrials(DataSpike,Trials);
    DataSpike = getSolo_K_ConditionTrials(DataSpike,Trials);
    DataSpike = getAreaTrials(DataSpike,Trials);
    DataSpike = getGoodNeurons(DataSpike,Trials);
    % DataSpike=    getTuningSoloNeurons(S,Trials);
    % DataSpike=    getTuningJointNeurons(S,Trials);
    % DataSpike=    getTuningObsNeurons(S,Trials);
    % DataSpike=    getTuningNoSoloNeurons(S,Trials);
    % DataSpike=    getTuningNoJointNeurons(S,Trials);
    % DataSpike=    getTuningNoObsNeurons(S,Trials);
    % if length(CELL_SELECTION)>1
    %     DataSpike=        getTuningNeurons(S,Trials,CELL_SELECTION(2));
    %     DataSpike=        getNoTuningNeurons(S,Trials,CELL_SELECTION(2));
    % end
    DataSpike = getTimeMovementOnsetTargetTrials(DataSpike,Trials); %% new entry
    for ind=1:8
        DataSpike = getTConditionTrials(DataSpike,Trials,ind);
    end
    DataSpike = getTimeTargetTrials(DataSpike,Trials);
    %S=retuneSpikeWithTimeStamp1(S,Trials);
    if MODE_ALIGN==1 %TARGET_APPEARS_MODE
        DataSpike = retuneSpikeWithTargetAppears(DataSpike,Trials);
    elseif MODE_ALIGN==0 %MOVEMENT_ONSET_MODE
        DataSpike = retuneSpikeWithMovementOnset(DataSpike,Trials);
    elseif MODE_ALIGN==2 %MOVEMENT_ONSET_K_MODE
        DataSpike = retuneSpikeWithMovementOnsetK(DataSpike,Trials);
    elseif MODE_ALIGN==3 %MOVEMENT_ONSET_S_MODE
        DataSpike = retuneSpikeWithMovementOnsetS(DataSpike,Trials);
    end

    DataSpike = prepareSpikeAndTrials(DataSpike,Trials,interval,selMonkey);

    dat = DataSpike.dat;
    data_session = dat;

    % time vector
    t = linspace(interval(1), interval(2), size(dat(1).spikes,2));

    dataSession_trials = struct();

    for iTr=1:length(data_session)
        dataSession_trials(iTr).trialId                = data_session(iTr).trialId;
        dataSession_trials(iTr).timeSpikes             = t;
        dataSession_trials(iTr).Spikes                 = data_session(iTr).spikes;
        dataSession_trials(iTr).trialTypeDir           = data_session(iTr).trialType;
        dataSession_trials(iTr).trialTypeCond          = data_session(iTr).trialType2;
        dataSession_trials(iTr).SessName               = session_list{n_sess};
        dataSession_trials(iTr).chamber                = chamber;
    end

    dataSession_trials(1).All_N_Identity               = DataSpike.AllNeuronIdentity;
    dataSession_trials(1).All_Good_N_Identity          = DataSpike.AllGoodNeuronIdentity;

    dataSession_trials                                 = conditionalligne(dataSession_trials);
    % saving single session data
    dirSingle = params.singleDir_save;
    save_path = fullfile( ...
        pwd,...
        dirSingle,...
        ['BOOT',num2str(M)],...
        num2str(params.irng),...
        'Single_SpikesExtractedBOOT',...
        params.chamber);
    if ~exist(save_path, 'dir')
        mkdir(save_path);
    end
    
    ch = dataSession_trials(1).chamber;
    if iscell(ch)
        ch = ch{1};
    end

    name_save = sprintf('%s_%g_%g_%s_%s', ...
                selMonkey, interval(1), interval(2), ch, session_name);
save(fullfile(save_path, strcat(name_save,'.mat')), 'dataSession_trials');
end

f_pattern = [save_path, filesep,params.selMonkey,'_',num2str(interval(1)),'_',num2str(interval(2)),'_',params.chamber,'*.mat'];

% Full path
M_files = dir(f_pattern);

disp("Files found:");
disp({M_files.name});

sess_temp = erase(session_list, 'SK');
session_num = str2double(sess_temp);

dataSessions = cell(1, length(session_num));
for k = 1:length(M_files)
    fullname = fullfile(M_files(k).folder, M_files(k).name);

    fprintf('Loading %s\n', fullname);

    loaded = load(fullname);
    % Extract session number with a not found warning
    tokens = regexp(M_files(k).name,'SK(\d+)','tokens');
    if isempty(tokens)
        warning("File %s: can't find session number", M_files(k).name);
        continue;
    end
    sess_nb = str2double(tokens{1}{1});

    idx = find(session_num == sess_nb);

    if isempty(idx)
        warning('Session %d is not in session_list, skipping.', sess_nb);
        continue;
    end

    data_trials_load = loaded.dataSession_trials;
    dataSessions{idx} = data_trials_load;
end

%% find max and min values for condition and direction and select the
% the appropriate neurons according to Goocells mat(s)
% output a new list of sessions including new fields (correct neurons for
% either monkey S and K)
totTrials = 0;
for k = 1:numel(session_num)
    totTrials = totTrials + numel(dataSessions{k});
end

all_cond = zeros(1, totTrials);
all_dir  = zeros(1, totTrials);

idx = 1;

for k = 1:numel(session_num)

    curr_sess = dataSessions{k};

    if isempty(curr_sess)
        error("Empty session %d: dataSessions{%d} = []", session_num(k), k);
    end

    all_n_id = curr_sess(1).All_N_Identity;
    if size(unique(all_n_id,'rows'),1) ~= size(all_n_id,1)
        error("Duplicates in neurons! Sessione %d", session_num(k));
    end

    n = numel(curr_sess);

    all_cond(idx:idx+n-1) = [curr_sess.trialTypeCond];
    all_dir(idx:idx+n-1)  = [curr_sess.trialTypeDir];

    idx = idx + n;
end

max_dir     = max(all_dir);
% min_dir     = min(all_dir);
max_cond    = max(all_cond);
% min_cond    = min(all_cond);
% tag direction-condition
dataSessions_new = cell(size(dataSessions));
if strcmp(params.chamber,'Frontal')
    GK = load('GoodCells_K_frontal.mat');
    GS = load('GoodCells_S_frontal.mat');
else
    GK = load('GoodCells_K_parietal.mat');
    GS = load('GoodCells_S_parietal.mat');
end
for k=1:numel(session_num)
    curr_sess_id    = session_num(k);
    curr_sess       = dataSessions{k};
    all_n_id        = curr_sess(1).All_N_Identity;

    % matching neurons
    Good_K          = GK.GoodCells_K(GK.GoodCells_K(:,1)==curr_sess_id,:);
    Good_S          = GS.GoodCells_S(GS.GoodCells_S(:,1)==curr_sess_id,:);

    [~,~,intGood_k]       = intersect(Good_K(:,2:3),  all_n_id,'rows');
    [~,~,intGood_s]       = intersect(Good_S(:,2:3),  all_n_id,'rows');

    N               = numel(curr_sess);
    combo_counter   = zeros(1, max_cond*max_dir);

    for i = 1:N
        Spikes                                      = curr_sess(i).Spikes;
        cond                                        = curr_sess(i).trialTypeCond;
        direction                                   = curr_sess(i).trialTypeDir;
        tag                                         = (cond-1)*max_dir+direction;
        combo_counter(tag)                          = combo_counter(tag)+1;
        curr_sess(i).tag                            = combo_counter(tag);
        curr_sess(i).S_spikes                       = Spikes(intGood_s,:);
        curr_sess(i).K_spikes                       = Spikes(intGood_k,:);
        curr_sess(i).Neuron_S.All_N_Id_Position     = intGood_s;
        curr_sess(i).Neuron_S.Good                  = Good_S;
        curr_sess(i).Neuron_K.All_N_Id_Position     = intGood_k;
        curr_sess(i).Neuron_K.Good                  = Good_K;
    end

    dataSessions_new{k}  = curr_sess;
end

% 
%% Generating S and K data matrix joining session
totN = 0;
for j = 1:numel(dataSessions_new)
    totN = totN + numel(dataSessions_new{j});
end

all_tags = zeros(1, totN);   % oppure false / categorical

idx = 1;
for j = 1:numel(dataSessions_new)
    curr                    = dataSessions_new{j};
    n                       = numel(curr);
    all_tags(idx:idx+n-1)   = [curr.tag];
    idx                     = idx + n;
end

POOL = cell( max_cond, max_dir,numel(dataSessions_new));

for j = 1:numel(dataSessions_new)

    curr_sess = dataSessions_new{j};

    for t = 1:numel(curr_sess)
        cc = curr_sess(t).trialTypeCond;
        dd = curr_sess(t).trialTypeDir;
        POOL{cc,dd,j} = [POOL{cc,dd,j}, t];

    end
end


%max_tag = max(all_tags);
%min_tag = min(all_tags);

max_tag = M;
S_final = cell(max_cond, max_dir, max_tag);
K_final = cell(max_cond, max_dir, max_tag);

trialId_final           = cell(max_cond, max_dir, max_tag);
trialSession_final      = cell(max_cond, max_dir,max_tag);
timeSpikes_final        = cell(max_cond, max_dir, max_tag);
chamber_final           = cell(max_cond, max_dir, max_tag);
Neuron_final_S          = cell(max_cond, max_dir, max_tag);
Neuron_final_K          = cell(max_cond, max_dir, max_tag);

% for j = 1:numel(dataSessions_new)
%     curr_sess = dataSessions_new{j};
%     for i = 1:numel(curr_sess)
%         cond = curr_sess(i).trialTypeCond;
%         direction  = curr_sess(i).trialTypeDir;
%         tag  = curr_sess(i).tag;
% 
%         S_final{cond, direction, tag}             = [S_final{cond, direction, tag}; curr_sess(i).S_spikes];
%         K_final{cond, direction, tag}             = [K_final{cond, direction, tag}; curr_sess(i).K_spikes];
%         trialId_final{cond, direction, tag}       = [trialId_final{cond, direction, tag}; curr_sess(i).trialId];
%         trialSession_final{cond, direction, tag}  = [trialSession_final{cond, direction, tag}; {curr_sess(i).SessName}];
%         timeSpikes_final{cond, direction, tag}    = [timeSpikes_final{cond, direction, tag}; curr_sess(i).timeSpikes];
%         chamber_final{cond, direction, tag}       = [chamber_final{cond, direction, tag};{curr_sess(i).chamber}];
%         Neuron_final_S{cond, direction, tag}      = [Neuron_final_S{cond, direction, tag};curr_sess(i).Neuron_S];
%         Neuron_final_K{cond, direction, tag}      = [Neuron_final_K{cond, direction, tag};curr_sess(i).Neuron_K];
%     end
% end


for cc = 1:max_cond
    for dd = 1:max_dir
        for m=1:M
            for j = 1:numel(dataSessions_new)
                % trial compatibili
                idx = POOL{cc,dd,j};
                if isempty(idx)
                    continue
                end
                k=idx(randi(numel(idx)));
                curr_sess = dataSessions_new{j};
                S_final{cc, dd, m} = [S_final{cc, dd, m}; curr_sess(k).S_spikes];
                K_final{cc, dd, m} = [K_final{cc, dd, m}; curr_sess(k).K_spikes];
                trialId_final{cc, dd,m}       = [trialId_final{cc, dd, m}; curr_sess(k).trialId];

                trialSession_final{cc, dd, m}  = [trialSession_final{cc, dd, m}; {curr_sess(k).SessName}];

                timeSpikes_final{cc, dd, m}   = [timeSpikes_final{cc, dd, m}; curr_sess(k).timeSpikes];
                chamber_final{cc, dd, m}       = [chamber_final{cc, dd, m};{curr_sess(k).chamber}];
                Neuron_final_S{cc, dd, m}      = [Neuron_final_S{cc, dd, m};curr_sess(k).Neuron_S];
                Neuron_final_K{cc, dd, m}      = [Neuron_final_K{cc, dd, m};curr_sess(k).Neuron_K];
            end
        end
    end
end




data = struct( ...
    'trialID',         [], ...
    'trialIdSession',  {}, ...
    'timeSpikes',      [], ...
    'trialTypeCond',   [], ...
    'trialTypeDir',    [], ...
    'S_Spikes',        [], ...
    'K_Spikes',        [], ...
    'Tag',             []);



% for cc = 1:max_cond
%     for dd = 1:max_dir
%         for tt = 1:max_tag
%             S_s = S_final{cc,dd,tt};
%             K_k = K_final{cc,dd,tt};
% 
%             if isempty(S_s) && isempty(K_k)
%                 continue
%             end
% 
%             prod = prod + 1;
% 
%             data(prod).trialID          = trialId_final{cc,dd,tt};
%             data(prod).trialIdSession   = trialSession_final{cc,dd,tt};
%             data(prod).timeSpikes       = timeSpikes_final{cc,dd,tt};
%             data(prod).trialTypeCond    = cc;
%             data(prod).trialTypeDir     = dd;
%             data(prod).Tag              = tt;
% 
%             data(prod).S_Spikes         = S_s;
%             data(prod).K_Spikes         = K_k;
% 
%             data(prod).chamber          = chamber_final{cc,dd,tt};
%             data(prod).Neuron.S         = Neuron_final_S{cc,dd,tt};
%             data(prod).Neuron.K         = Neuron_final_K{cc,dd,tt};
% 
%         end
%     end
% end


prod =0;

for cc = 1:max_cond
    for dd = 1:max_dir    
        for m=1:M
            S_s = S_final{cc,dd,m};
            K_k = K_final{cc,dd,m};

            if isempty(S_s) && isempty(K_k)
                continue
            end

            prod = prod + 1;

            data(prod).trialID          = trialId_final{cc,dd,m};
            data(prod).trialIdSession   = trialSession_final{cc,dd,m};
            data(prod).timeSpikes       = timeSpikes_final{cc,dd,m};
            data(prod).trialTypeCond    = cc;
            data(prod).trialTypeDir     = dd;
            data(prod).Tag              = m;

            data(prod).S_Spikes         = S_s;
            data(prod).K_Spikes         = K_k;

            data(prod).chamber          = chamber_final{cc,dd,m};
            data(prod).Neuron.S         = Neuron_final_S{cc,dd,m};
            data(prod).Neuron.K         = Neuron_final_K{cc,dd,m};

        end
    end
end

%% tag filtering
data_trials_BS = data;
% data_trials_BS = data([data.Tag]<=8); 
% Keep only the first 192 trials (8 per condition and direction). 
% Any subsequent trials are discarded to ensure temporal alignment 
% across all sessions, including those with missing data.

saveDir = fullfile(params.dir_save, 'All_SpikesExtractedBOOT');
if ~exist(saveDir,'dir')
    mkdir(saveDir);
end

nameDataSave = params.selMonkey;
nameboot = 'BOOT';
saveName = [nameDataSave,'_', params.chamber,'_',...
    num2str(interval(1)),'_',...
    num2str(interval(2)),'_',...
    nameboot,num2str(M)];

saveName = [saveName,'_irng',num2str(params.irng),'.mat'];

save( ...
    fullfile(saveDir,saveName), ...
    'data_trials_BS', ...
    'params', ...
    '-v7.3');

    function modeStr = modeAlignToString(MODE_ALIGN)
        switch MODE_ALIGN
            case 1
                modeStr = 'Target ON';
            case 0
                modeStr = 'Movement Onset';
            case 2
                modeStr = '"K" Movement Onset';
            case 3
                modeStr = '"S" Movement Onset';
            otherwise
                modeStr = 'Unknown alignment mode';
        end
    end
end